# - subset variables ----
library(datasets) # datasets library for sample data...
data(iris) # import into the r enviroment... 
data = iris # store the iris dataframe as 'data' in the r enviroment...
remove = c("Petal.Width")
data = data[, !colnames(data) %in% c(remove)] # conditionally select the variables to remove from the dataframe. 
print(str(data))